version: '3'

services:
 kong-database:
  image: postgres:9.4
  container_name: kong_database
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong
  ports:
    - "5432:5432"

 kong:
  image: kong:0.10.1
  container_name: kong
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
  ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
    - "7946:7946"
    - "7946:7946/udp"
  links:
    - "kong-database:kong_database"
